#!/usr/bin/env python3
"""Generate static, shareable player profile pages from data/seasons.json."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


GENERATED_MARKER = "<!-- Generated by scripts/generate_player_pages.py. Do not edit directly. -->"


def render_profile(template: str, profile: dict[str, object]) -> str:
    name = str(profile["name"])
    profile_id = str(profile["id"])
    title = f"{name} Golf Stats | City League"
    description = (
        f"Career and season-by-season City League golf stats for {name}, "
        "including gross scores, net scores, and handicap history."
    )
    replacements = {
        "{{PROFILE_ID}}": html.escape(profile_id, quote=True),
        "{{PLAYER_NAME}}": html.escape(name),
        "{{PAGE_TITLE}}": html.escape(title),
        "{{DESCRIPTION}}": html.escape(description, quote=True),
    }
    page = template
    for token, value in replacements.items():
        page = page.replace(token, value)
    return f"{GENERATED_MARKER}\n{page}"


def player_index() -> str:
    return f"""{GENERATED_MARKER}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="refresh" content="0; url=../player-stats.html#player-standings" />
    <link rel="canonical" href="https://cityleaguestats.com/player-stats.html#player-standings" />
    <title>City League Players</title>
  </head>
  <body>
    <p><a href="../player-stats.html#player-standings">View all City League players</a></p>
  </body>
</html>
"""


def profile_redirect(profile: dict[str, object]) -> str:
    profile_id = html.escape(str(profile["id"]), quote=True)
    player_name = html.escape(str(profile["name"]))
    return f"""{GENERATED_MARKER}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="refresh" content="0; url={profile_id}.html" />
    <link rel="canonical" href="https://cityleaguestats.com/players/{profile_id}.html" />
    <title>{player_name} Golf Stats | City League</title>
  </head>
  <body>
    <p><a href="{profile_id}.html">View {player_name}’s current player profile</a></p>
  </body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path("data/seasons.json"))
    parser.add_argument(
        "--template", type=Path, default=Path("templates/player-page.html")
    )
    parser.add_argument("--output", type=Path, default=Path("players"))
    args = parser.parse_args()

    store = json.loads(args.data.read_text(encoding="utf-8"))
    template = args.template.read_text(encoding="utf-8")
    profiles = store.get("playerProfiles", [])
    if not profiles:
        raise SystemExit("No playerProfiles found. Run scripts/parse_emails.py first.")

    args.output.mkdir(parents=True, exist_ok=True)
    expected = {f"{profile['id']}.html" for profile in profiles}
    legacy_redirects: dict[str, dict[str, object]] = {}
    for profile in profiles:
        for legacy_id in profile.get("legacyIds", []):
            legacy_name = f"{legacy_id}.html"
            if legacy_name in expected or legacy_name in legacy_redirects:
                raise SystemExit(f"Duplicate legacy player profile ID: {legacy_id}")
            legacy_redirects[legacy_name] = profile
    expected.update(legacy_redirects)
    expected.add("index.html")

    for existing in args.output.glob("*.html"):
        if existing.name not in expected:
            start = existing.read_text(encoding="utf-8", errors="ignore")[:160]
            if GENERATED_MARKER in start:
                existing.unlink()

    for profile in profiles:
        target = args.output / f"{profile['id']}.html"
        target.write_text(render_profile(template, profile), encoding="utf-8")

    for legacy_name, profile in legacy_redirects.items():
        (args.output / legacy_name).write_text(
            profile_redirect(profile), encoding="utf-8"
        )

    (args.output / "index.html").write_text(player_index(), encoding="utf-8")
    print(f"Generated {len(profiles)} player pages in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
